version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: deps
    labels:
      - dependencies
